"""create safety_evaluations table

Revision ID: 13cda6c930c1
Revises: 3d7165a43ae7
Create Date: 2026-08-17 01:37:10.487497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13cda6c930c1'
down_revision: Union[str, None] = '3d7165a43ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_evaluations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('message_index', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('matched_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('classifier_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('NORMAL', 'MODERATE', 'HIGH_RISK')", name='ck_safety_eval_risk_level'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'message_index', name='uq_safety_eval_session_idx')
    )
    op.create_index('ix_safety_eval_category', 'safety_evaluations', ['category'], unique=False)
    op.create_index('ix_safety_eval_risk_level', 'safety_evaluations', ['risk_level'], unique=False)
    op.create_index('ix_safety_eval_session_created', 'safety_evaluations', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_safety_eval_session_created', table_name='safety_evaluations')
    op.drop_index('ix_safety_eval_risk_level', table_name='safety_evaluations')
    op.drop_index('ix_safety_eval_category', table_name='safety_evaluations')
    op.drop_table('safety_evaluations')
    # ### end Alembic commands ###